### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by lyandy** [summerHearts/SystemAuthorizationManager#1]
1. confrimBlock 单词拼错
2. 注意书写规范，注意添加空格，注意枚举类型的写法，看一下系统怎么写枚举的

**Comment by summerHearts** [comment]
已经修改完毕：
     typedef NS_ENUM(NSInteger, KSystemPermissions) {
    
    KAVMediaTypeVideo = 0,  // 相机
    KALAssetsLibrary,       //相册
    KCLLocationManager,     //地理位置信息
    KAVAudioSession,        //音频
    KABAddressBook          //手机通讯录
};

添加了注释和通用信息：
static NSString *const APPNAME = @"";  //填写自己APP NAME
